language: go
go:
 - 1.8

sudo: required
services:
  - docker

env:
  - TRAVIS_NODE_VERSION="7"

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  # Repo for Yarn
  - npm install -g yarn

cache:
  yarn: true
  directories:
    - ui/node_modules

script:
  - go get -u github.com/lestrrat/go-bindata/...
  - pushd ui && yarn install && popd
  # Ensure all js is formatted. gopherCI takes care of Go
  - yarn global add prettier --ignore-engines
  - prettier --write "ui/**.js"
  - go generate $(go list ./... | grep -v vendor)
  - test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }
  - go test -race -v ./...

notifications:
  slack: hydrocarbon:czrQMquiw5uA7yR3mhpMrdQM
  email: false
